## Demo playbook for Setting up First EC2 Instance
# 1) Create a custom security group
# 2) Spins up new Ec2 Instances
# 3) Waits for ssh to become active on Instance
#
# Version 1.0
- hosts: localhost
  tasks:
   - name: Setting up Security/Firewall Group
     ec2_group:
       name: Raham_AWS_Security_Group
       description: Rules Allowing Trafic on port 22 and 80
       region: us-west-2
       rules:
         - proto: tcp
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: 0.0.0.0/0
       rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
   - name: Provision a Ec2 Instance
     ec2:
        key_name: raham_awskey
        region: us-west-2
        instance_type: t2.micro
        image: ami-775e4f16
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          name: awslabserver
          owner: Rahamthulla
        monitoring: no
        vpc_subnet_id: subnet-9253of4
        assign_public_ip: yes
        group: Raham_AWS_Security_Group
     register: ec2-out
     
   - name: Wait for SSH to come up
     wait_for: host={{ item.public_dns_name}} port=22 dely=60 timeout=320 state=started
     with_item: '{{ec2_out.instances}}'
